In [55]:
from sklearn.svm import LinearSVC
from sklearn.svm import SVC
import pandas as pd
from sklearn import preprocessing
import numpy as np
import sklearn as sk
from sklearn.neural_network import MLPClassifier 
from sklearn.linear_model import LogisticRegression
from sklearn import linear_model
from sklearn.preprocessing import PolynomialFeatures
from sklearn import ensemble
from sklearn.metrics import f1_score
from sklearn.model_selection import train_test_split

np.random.seed(1)

In [3]:
train = pd.read_csv("train.csv")
test = pd.read_csv("test.csv")

In [16]:
X1 = train["Sequence"]
y = train["Active"]
data = len(X1)

In [43]:
X2 = np.zeros(shape=(data,84))
letters = ["A","C","D","E","F","G","H","I","K","L","M","N","P","Q","R","S","T","U","V","W","Y"]
print(X2)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [45]:
for i in range(0, data):
    a = np.zeros(84)
    sequence = X1[i]
    for j in range(0,4):
        b = np.zeros(21)
        for k in range(0,21):
            if sequence[j] == letters[k]:
                b[k] = 1
        t = 21*j
        a[t:t+21] = b
        a = np.transpose(a)
    X2[i] = a

In [48]:
X3 = pd.DataFrame(X2)
print(X3)

         0    1    2    3    4    5    6    7    8    9   ...   74   75   76  \
0       0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
1       0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...  1.0  0.0  0.0   
2       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  1.0  0.0   
3       0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
4       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
...     ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
111995  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
111996  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
111997  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
111998  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  0.0  0.0   
111999  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   

         77   78   79   80   81   82   

In [58]:
clf = MLPClassifier(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(10,3), random_state=1)

In [59]:
X_train, X_test, y_train, y_test = train_test_split(X3,y,test_size=0.2,random_state=42)
clf.fit(X_train,y_train)
y_score = clf.predict(X_test)
f1_score(y_test, y_score)

0.8553379658875553